### ISSUE TITLE
Cannot fine the specified checkpoint.

### ISSUE THREAD

**Issue by jayendra-ram** [devJWSong/gpt2-chatbot-pytorch#7]
I have a checkpoint named test.cpkt but when I run  sh exec_infer.sh --ckpt_name="test" (with our without quotations, and with or without /gpt2), the script cant find the checkpoint. I'm guessing this is a really dumb syntax error.

**Comment by devjwsong** [comment]
Hi, thank you for your attention to this project.
If the script cannot find the checkpoint, I think this is because the checkpoint direction is not correctly specified.
The checkpoint directory is `{args.ckpt_dir}/{args.model_type}`.
Can you check again whether the model is properly contained in above directory?

**Comment by jayendra-ram** [comment]
I am now running sh exec_infer.sh --ckpt_name="test"  with test in the saved_models/gpt2 and it still can't find the checkpoint. Is there any more arguments I need?

**Comment by devjwsong** [comment]
Then is the extension of the checkpoint file `.ckpt`?
The script automatically append `.ckpt` extension at the end of `ckpt_name`. 

And it would be helpful if you show me the specific error log from your terminal.

**Comment by jayendra-ram** [comment]
<img width="796" alt="Screen Shot 2021-08-31 at 12 05 35 PM" src="https://user-images.githubusercontent.com/42985072/131537440-8f23211f-e596-45ac-b3e0-b29683af38f3.png">

apologies, here's a screenshot. Theres a seinfeld.ckpt in my saved_models/gpt2 folder

**Comment by devjwsong** [comment]
I just trained the model with the small amount of data and executed inference script just like you did.
I'm afraid that it works perfectly fine.
If you didn't modify the codes, then this would be a typo issue regarding the directory name or file name.

Please show me the entire shell script file `exec_infer.sh` and your file list in `saved_models/gpt2` directory.

(+) I recommend you to pull again since I just modified small error. I mistakenly pushed data truncation for testing before. I fixed so that the entire training data should be included.

**Comment by jayendra-ram** [comment]
<img width="701" alt="Screen Shot 2021-08-31 at 12 47 00 PM" src="https://user-images.githubusercontent.com/42985072/131543305-6f7b8245-dba4-44be-8c6d-5ea0b0aa4f61.png">
<img width="494" alt="Screen Shot 2021-08-31 at 12 47 41 PM" src="https://user-images.githubusercontent.com/42985072/131543381-9d6390df-978f-4991-b6b3-4aecc4e73fbe.png">

The two screens requested. Pulled again and getting the same error. Thank you for the help so far.

**Comment by devjwsong** [comment]
You didn't specify the checkpoint file name.
You should change `--ckpt_name=CKPT_NAME` into `--ckpt_name="seinfeld"` in `exec_infer.sh`.

**Comment by jayendra-ram** [comment]
Oh I see. So I have to change the arguments in the script as opposed to just in the command line. Thank you!

**Comment by devjwsong** [comment]
Yes. And I recommend you to retrain your model. Since I changed data loading part when I re-pushed.
